//! The head, as a Register record.
//!
//! The engine's head is `(seq, root)`, and a Register holds one signed value
//! per writer — so the head IS a Register record, and writing it means
//! signing one. This builds and signs that record.
//!
//! **The format is implemented here, not imported.** sdk#35 deliberately
//! decouples this repository's revision from the contracts', and a path
//! dependency on the Register crate would re-couple exactly what that
//! decision separates — the Register is also its own cargo workspace with a
//! pinned lockfile, because its wasm hash is part of every register's key.
//!
//! A second copy of a wire format is a thing that drifts, so what keeps this
//! one honest is not care: it is KNOWN-ANSWER VECTORS generated by the
//! authoritative implementation and pinned in `tests/register.rs`, which do
//! not descend from this code at all. sdk#35's artefact gate is the deeper
//! conformance check; these are the tripwire.
//!
//! Mode 0 only — a single writer key, which is what a device's own head is.
//! A k-of-n keyset head is a Phase 6 question (several devices), and this
//! refuses rather than guesses at it.

use ed25519_dalek::{Signer, SigningKey};

/// `RG01`, at the front of both the params and an encoded state.
const MAGIC: &[u8; 4] = b"RG01";
/// Domain separation: what a signature is over is never a bare hash.
const SIG_DOMAIN: &[u8; 8] = b"RG01-sig";
const KEY_LEN: usize = 32;
const HASH_LEN: usize = 32;
/// The state carries a record, and no equivocation evidence.
const FLAG_RECORD: u8 = 0b01;
/// A Register value is capped; the head is 32 bytes, far inside it.
const MAX_VALUE: usize = 4096;

/// Why a head could not be built.
#[derive(Debug, PartialEq, Eq)]
pub enum HeadError {
    /// The params are not a mode-0 Register's.
    ///
    /// Refused rather than guessed: mode 1 is a k-of-n keyset, and signing
    /// one slot of a quorum with a device key would produce a record that
    /// looks valid and decides nothing.
    NotSingleWriter,
    /// The signing key is not 32 bytes.
    BadKey,
    /// The value is over the Register's cap.
    ValueTooLong,
    /// The params name a key this delegate cannot sign for.
    ///
    /// Caught HERE rather than by the node: a record signed by the wrong key
    /// is refused on arrival, and the commit would then wait on a head that
    /// is never going to land.
    WrongWriter,
}

/// The writer key a mode-0 Register is created under.
fn writer_key(params: &[u8]) -> Result<[u8; KEY_LEN], HeadError> {
    let rest = params
        .strip_prefix(MAGIC)
        .ok_or(HeadError::NotSingleWriter)?;
    let (&mode, rest) = rest.split_first().ok_or(HeadError::NotSingleWriter)?;
    if mode != 0 {
        return Err(HeadError::NotSingleWriter);
    }
    let k = rest.get(..KEY_LEN).ok_or(HeadError::NotSingleWriter)?;
    let mut out = [0u8; KEY_LEN];
    out.copy_from_slice(k);
    Ok(out)
}

/// The bytes a writer signs for `(seq, value)` under these params.
///
/// Bound to the PARAMS and not to the contract code, so that after a code
/// upgrade the latest record can be re-published under the new code and still
/// verify.
fn signed_message(params_hash: &[u8; HASH_LEN], seq: u64, value_hash: &[u8; HASH_LEN]) -> Vec<u8> {
    let mut m = Vec::with_capacity(SIG_DOMAIN.len() + HASH_LEN + 1 + 8 + HASH_LEN);
    m.extend_from_slice(SIG_DOMAIN);
    m.extend_from_slice(params_hash);
    // `terminal` is false: a head is superseded by the next head, never final.
    m.push(0u8);
    m.extend_from_slice(&seq.to_le_bytes());
    m.extend_from_slice(value_hash);
    m
}

/// Build and sign the state that says "the head is `value` at `seq`".
pub fn head_state(
    params: &[u8],
    signing_key: &[u8],
    seq: u64,
    value: &[u8],
) -> Result<Vec<u8>, HeadError> {
    if value.len() > MAX_VALUE {
        return Err(HeadError::ValueTooLong);
    }
    let key: [u8; 32] = signing_key.try_into().map_err(|_| HeadError::BadKey)?;
    let sk = SigningKey::from_bytes(&key);
    let want = writer_key(params)?;
    if sk.verifying_key().to_bytes() != want {
        return Err(HeadError::WrongWriter);
    }

    let params_hash: [u8; HASH_LEN] = *blake3::hash(params).as_bytes();
    let value_hash: [u8; HASH_LEN] = *blake3::hash(value).as_bytes();
    let sig = sk.sign(&signed_message(&params_hash, seq, &value_hash));

    // RG01 | flags | terminal | seq | vlen | value | sig
    let mut out = Vec::from(*MAGIC);
    out.push(FLAG_RECORD);
    out.push(0u8);
    out.extend_from_slice(&seq.to_le_bytes());
    let vlen = u16::try_from(value.len()).unwrap_or(u16::MAX);
    out.extend_from_slice(&vlen.to_le_bytes());
    out.extend_from_slice(value);
    out.extend_from_slice(&sig.to_bytes());
    Ok(out)
}
