//! Writes `js/instrument-vocab.js`: the vocabulary the SDK's LOADER records in (sdk#386's instrument work, the
//! architect's design), for the JS that runs BEFORE the SDK's wasm exists (`js/served.js`).
//!
//! The loader cannot ask the wasm, and it must not keep a second copy of a fact (the owner's rule 3). So every value
//! here is PRODUCED from its one owner: the page's closed loader code lists (`page::loader`) and the instrument
//! crate's own tables (StatusClass codes, the HTTP classification, the coarsening bands). The page validates every
//! code the loader hands it against the same lists. `build.sh` runs this; the output is generated, never edited, and
//! a test fails when it is stale.
//!
//!   cargo run -q -p page --example instrument_js > js/instrument-vocab.js

use instrument::vocab::{StatusClass, COARSEN_BANDS, COARSEN_LAST_GRAIN, HTTP_CLASSES};
use page::loader;

fn object(pairs: impl IntoIterator<Item = (String, u64)>) -> String {
    let body = pairs.into_iter().map(|(k, v)| format!("{k:?}: {v}")).collect::<Vec<_>>().join(", ");
    format!("Object.freeze({{ {body} }})")
}

fn main() {
    println!("// GENERATED by `cargo run -p page --example instrument_js` (build.sh); do not edit.");
    println!("// The loader's recording vocabulary: page/src/loader.rs's closed code lists and craftworks-instrument's tables.");
    println!("// Every event is STRIDE numbers, [kind, site, a, b, c]; the page validates each against the same lists.");
    println!("export const STRIDE = {};", loader::STRIDE);
    println!("export const EVENT = {};", object([("EDGE".into(), loader::EDGE), ("EXIT".into(), loader::EXIT), ("COUNTER".into(), loader::COUNTER)]));
    println!("export const SITE = {};", object(loader::SITES.iter().enumerate().map(|(i, s)| (s.name().to_string(), i as u64))));
    println!("export const KEY = {};", object(loader::KEYS.iter().enumerate().map(|(i, k)| (format!("{k:?}"), i as u64))));
    println!("export const OUTCOME = {};", object(loader::OUTCOMES.iter().enumerate().map(|(i, o)| (format!("{o:?}"), i as u64))));
    println!("export const STATUS = {};", object(StatusClass::ALL.iter().map(|c| (format!("{c:?}"), c.code()))));
    let http = HTTP_CLASSES.iter().map(|(lo, hi, c)| format!("[{lo}, {hi}, {}]", c.code())).collect::<Vec<_>>().join(", ");
    println!("// An HTTP status's class: the first [lowest, highest, class] that holds it, else STATUS.OtherHttp.");
    println!("export const HTTP_CLASSES = Object.freeze([{http}]);");
    let bands = COARSEN_BANDS.iter().map(|(below, grain)| format!("[{below}, {grain}]")).collect::<Vec<_>>().join(", ");
    println!("// A time, coarsened: round down to the grain of the first [below, grain] band it is under, else COARSEN_LAST_GRAIN.");
    println!("export const COARSEN_BANDS = Object.freeze([{bands}]);");
    println!("export const COARSEN_LAST_GRAIN = {COARSEN_LAST_GRAIN};");
}
