//! Writes `js/rto.js`: the page's RTO back-off, for the JS that runs BEFORE
//! the SDK's wasm exists (sdk#312).
//!
//! The app-code fetch (`js/artefacts.js`) is what fetches the wasm, so it
//! cannot ask the wasm's [`page::rto::Rto`] how long to wait. It must not
//! write a second back-off either (the owner's rule 3: one owner per fact).
//! So the schedule is PRODUCED by the real `Rto` — timed out again and again,
//! from no sample, until it stops moving — and the JS only walks the list.
//! `build.sh` runs this; the output is generated, never edited.
//!
//!   cargo run -q -p page --example rto_js > js/rto.js

fn main() {
    let mut rto = page::rto::Rto::default();
    let mut schedule = vec![rto.rto_ms()];
    loop {
        rto.timed_out();
        let next = rto.rto_ms();
        if next == *schedule.last().expect("never empty") {
            break;
        }
        schedule.push(next);
    }
    let list = schedule.iter().map(u64::to_string).collect::<Vec<_>>().join(", ");
    println!("// GENERATED by `cargo run -p page --example rto_js` (build.sh); do not edit.");
    println!("// The page's RTO back-off from no sample (page/src/rto.rs, RFC 6298 §5.5):");
    println!("// each wait after an unanswered ask, the last repeating for ever.");
    println!("export const RTO_SCHEDULE_MS = Object.freeze([{list}]);");

    // THE WINDOW (sdk#347): how many GETs may be in flight after n answers, from a new page's window
    // (page::rto::Window, slow start, no loss yet). The load-piece race walks this list; it keeps no window rule of
    // its own. 64 entries: more than any k + m the codec allows (MAX_K + MAX_M = 44).
    let mut w = page::rto::Window::default();
    let mut sizes = Vec::new();
    for _ in 0..64 {
        sizes.push(w.size());
        w.opened();
    }
    let sizes = sizes.iter().map(usize::to_string).collect::<Vec<_>>().join(", ");
    println!("// How many GETs a new page keeps in flight after n answers (page/src/rto.rs `Window`, slow start):");
    println!("// the load-piece race's pacing (sdk#347). The last entry holds from then on.");
    println!("export const WINDOW_AFTER_ANSWERS = Object.freeze([{sizes}]);");
}
